### ISSUE TITLE
Minimum threshold for overlaps?

### ISSUE THREAD

**Issue by fmaussion** [ezwelty/rgi_links#6]
I am in the process of including the links to RGI6 in the RGI7 workflow (I already used the tools to filter self-overlaps - thanks!!!!).

I have a question / discussion regarding what we should deliver to the user. As of now, `compute_cross_overlaps` is very precise and returns *everything*. For example, with RGI01 (unchanged in most parts), the tool returns 50574 overlaps for 27511 geometries, which many clusters looking like this:

![image](https://github.com/ezwelty/rgi_links/assets/10050469/8c89712a-59d7-4ee3-b082-a2a9bac3b7fd)

That's basically rounding error. The question is: **do we want to deliver this "as is" to RGI users, and they can filter themselves, or do we help them a little on the way?**

If we do help them (I think we should), we could add a `min_area` kwarg to `compute_cross_overlaps` which ignores smaller overlaps. **If we do that, what is a good min area?** Using 9500 m2 as for the filtering is not good, because this is way too large. 

Another way would be to add heuristics on fraction overlap, i.e. if two entities overlap by 99% than we round up to 100 and filter it out.

Thoughts? @ezwelty  @iamdonovan

**Comment by ezwelty** [comment]
@fmaussion I agree that some nominal amount of filtering is reasonable. Regarding implementation, I would rather filter the pairwise overlaps in a separate function. And I would not round `i_area_fraction`, `j_area_fraction` to 1 (and `area` to the minimum of the area of `i` and `j`), but rather just remove the offending rows before proceeding to populating the additional columns (`in`, `jn`, `cluster`). Simpler and more transparent and no less user friendly I think?

Filtering the 380998 overlaps between RGI 6.0 and 7.0 (the version you originally shared with me):

`i_area_fraction < 0.01 and j_area_fraction < 0.01` yields 106312 overlaps. The `area` of these overlaps is plotted below:

![image](https://github.com/ezwelty/rgi_links/assets/377523/21286fed-eea9-44e9-af7c-510780f4b321)

The max (9069649 m2) is from two neighboring giants in Arctic Canada that are drawn somewhat differently in the two datasets:

![image](https://github.com/ezwelty/rgi_links/assets/377523/1bca9810-215a-42ba-914d-db378e752aa6)

So maybe this is slightly too aggressive? Alternatively, we can filter just (or also) by area. `area < 100` (in the shoulder of the histogram above) yields 80134 overlaps, all of which have low `*_area_fraction` (max: 0.00856).

**Comment by fmaussion** [comment]
Thanks for having such a precise look! Yes 1% is obviously not good enough. Looking at the bimodal distribution it looks a little bit like this:

![image](https://github.com/ezwelty/rgi_links/assets/10050469/7e4aa204-9650-412d-895f-48743594b7a7)

So probably an area based threshold may be better than a % based one...

**Comment by ezwelty** [comment]
@fmaussion Exactly, that is what I meant when I wrote:

> Alternatively, we can filter just (or also) by area. `area < 100` (in the shoulder of the histogram above) yields 80134 overlaps, all of which have low `*_area_fraction` (max: 0.00856).

Here is a more complete histogram of all overlap areas (not just those with `*_area_fraction < 0.01):

![image](https://github.com/ezwelty/rgi_links/assets/377523/e1592156-94fe-4550-bdc9-359e95651b60)

There are actually three peaks: rounding error, "not legit", "legit". If I fit a smoothing cubic spline (orange) to a histogram of log area (blue) and find the minimum between the two large peaks, I end up with something hovering around 200 m2. `area < 200` yields 82553 overlaps, all of which have low `*_area_fraction` (max: 0.0203). Combined with `*_area_fraction < 0.01` yields 82532 overlaps.

How aggressive we should be depends on the use case. If it was just a matter of finding the best match between RGI6 and RGI7, we would filter on the set of overlaps for each glacier. But if it is just a matter of removing the "noise", then a simple minimum `area` seems appropriate.

**Comment by ezwelty** [comment]
Done: https://github.com/ezwelty/rgi_links#compute-rgi7-rgi6-overlaps
